In [1]:
import tensorflow

INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


In [2]:
import numpy as np

In [15]:
a = np.ones((3, 2))

In [16]:
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
b = np.ones((2, 3))

In [7]:
b

array([[1., 1., 1.]])

In [17]:
np.dot(b, a)

array([[3., 3.],
       [3., 3.]])